In [2]:
import sys
!{sys.executable} -m pip install xgboost

In [27]:
pip install bayesian-optimization

  Created wheel for bayesian-optimization: filename=bayesian_optimization-1.2.0-py3-none-any.whl size=11689 sha256=82fb21daa160f984eba8b7a31b28e0d382fef90f4f7bf894eca43a4f62e4c3a3
  Stored in directory: c:\users\harsh\appdata\local\pip\cache\wheels\fd\9b\71\f127d694e02eb40bcf18c7ae9613b88a6be4470f57a8528c5b
Successfully built bayesian-optimization
Note: you may need to restart the kernel to use updated packages.


In [100]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from bayes_opt import BayesianOptimization
from sklearn.metrics import mean_squared_error
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix,classification_report

## loading the data.

In [95]:
data=pd.read_csv("xboost.csv")

In [68]:
data.head()

course_id  thread_id  no_of_posts  no_of_comments  no_uni_users  \
0  analysenumerique-001          2          9.0             2.0           5.0   
1  analysenumerique-001          2          9.0             2.0           5.0   
2  analysenumerique-001          2          9.0             2.0           5.0   
3  analysenumerique-001          2          9.0             2.0           5.0   
4  analysenumerique-001          2          9.0             2.0           5.0   

   no_of_anonymous_msg  staff_replied  no of msgs  avg_num_words  max_words  \
0                  2.0            0.0        11.0      12.454545       31.0   
1                  2.0            0.0        11.0      12.454545       31.0   
2                  2.0            0.0        11.0      12.454545       31.0   
3                  2.0            0.0        11.0      12.454545       31.0   
4                  2.0            0.0        11.0      12.454545       31.0   

   avg_resp_time  first_post_day      msg_rate  u_chain  index_longest_post  \
0 -152871.727273               2  1.359260e+09     True                   4   
1 -152871.727273               2  1.359260e+09     True                   4   
2 -152871.727273               2  1.359260e+09     True                   4   
3 -152871.727273               2  1.359260e+09     True                   4   
4 -152871.727273               2  1.359260e+09     True                   4   

   num_views  votes  votes_Square  index_max_votes  forum_id  
0        277      2             4                0        10  
1        277      0             0                0        10  
2        277      1             1                0        10  
3        277      0             0                0        10  
4        277      0             0                0        10

## Droping unwanted coloumns

In [96]:
final_data=data.drop('course_id', axis=1)

## dividing data set to testing and training sets

In [97]:
x=final_data.drop('forum_id', axis=1)
y=final_data.forum_id
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train.head()

thread_id  no_of_posts  no_of_comments  no_uni_users  \
299806       6675         22.0            10.0          28.0   
153696         18         18.0            12.0          19.0   
629484        439          7.0             1.0           5.0   
359718       2509         31.0             6.0          33.0   
639718        344         28.0            15.0          20.0   

        no_of_anonymous_msg  staff_replied  no of msgs  avg_num_words  \
299806                  4.0            0.0        32.0      60.937500   
153696                  0.0            0.0        30.0      45.400000   
629484                  0.0            0.0         8.0      83.250000   
359718                  2.0            0.0        37.0      99.000000   
639718                  0.0            0.0        43.0      45.744186   

        max_words  avg_resp_time  first_post_day      msg_rate  u_chain  \
299806      315.0 -116637.250000               1  1.368940e+09     True   
153696      103.0 -107214.200000               3  1.365688e+09     True   
629484      401.0 -236928.000000               1  1.382590e+09     True   
359718      224.0  -16255.972973               0  1.367934e+09     True   
639718      210.0  -40776.395349               1  1.372209e+09     True   

        index_longest_post  num_views  votes  votes_Square  index_max_votes  
299806              299803        569      0             0           299775  
153696              153708        260      1             1           153680  
629484              629484        272      4            16           629484  
359718              359718        132      1             1           359710  
639718              639721        305      0             0           639710

## calling the XGboost classifier:

In [71]:
model = XGBClassifier()

## fitting the model

In [72]:
model.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [73]:
predict = model.predict(x_test)

## checking the Model accuracy:

In [74]:
accuracy_test = accuracy_score(y_test,predict)
accuracy_test

0.8348273179311978

## confusion matrix and classification report:

In [102]:
print(confusion_matrix(y_test,predict))
print(classification_report(y_test,predict))

[[ 7891 10327  2908   407  4837   443  7707]
 [ 9001 11624  3301   503  5458   507  8469]
 [ 2830  3759  1048   154  1826   161  2804]
 [  829  1088   310    49   538    54   798]
 [ 5201  6659  1745   285  3032   285  4927]
 [  828  1106   306    55   480    51   806]
 [ 7338  9837  2683   415  4485   418  7242]]
              precision    recall  f1-score   support

           2       0.23      0.23      0.23     34520
           3       0.26      0.30      0.28     38863
           4       0.09      0.08      0.08     12582
           7       0.03      0.01      0.02      3666
           8       0.15      0.14      0.14     22134
           9       0.03      0.01      0.02      3632
          10       0.22      0.22      0.22     32418

    accuracy                           0.21    147815
   macro avg       0.14      0.14      0.14    147815
weighted avg       0.20      0.21      0.21    147815



## Perform Hyper-parameter tuning on XGBoost

In [79]:
def tuning_function(n_estimators ,learning_rate):
     params = {'n_estimators': int(n_estimators),
              'learning_rate':learning_rate,
              'subsample': 0.8,
              'eta': 0.1,
              'eval_metric': 'rmse',
             'max_depth':int(4),
             'min_child_weight':6,
             'gamma':0,
             'subsample':0.8,
             'colsample_bytree':0.8,
             'reg_alpha':0.005,
             'objective': 'logistic',
             'nthread':4,
             'seed':27,
             'eta':0.1}

In [80]:
bayes = BayesianOptimization(tuning_function, {'n_estimators':(500,1000),
                                            'learning_rate':(0,0.5)
                                            })

In [81]:
params = bayes.max['params']
params['n_estimators']= int(params['n_estimators'])

KeyError: 'params'